### ISSUE TITLE
Versos y titulo 

### ISSUE THREAD

**Issue by vicentegro** [vicentegro/PercepcionN6Equipo18#3]
Agrega un par de versos sobre magia negra y añade un titulo al poema porfa.

**Comment by edercarrizales** [comment]
le puedo agregar mas sobre **magia** y **demonios** si quieres
![ferumbras](https://user-images.githubusercontent.com/42422377/44324857-84de4980-a41c-11e8-8393-d9c4a2b67375.jpg)

**Comment by edercarrizales** [comment]
#6 Puedo agregar mas sobre **magia** y **demonios** 
![ferumbras](https://user-images.githubusercontent.com/42422377/44325092-5a40c080-a41d-11e8-901c-3a2fdbf01c4b.jpg)
